/*
# Migración del esquema DBFACTURAS a Supabase

## Descripción
Crea todas las tablas del esquema DBFACTURAS original (SQL Server migrado a PostgreSQL)
con sus datos iniciales, procedimientos almacenados, función de consulta de facturas,
y políticas RLS para acceso desde la aplicación web.

## Tablas nuevas
1. tblcategoria_prod - Categorías de productos
2. tblroles - Roles de empleados
3. tblestado_factura - Estados de factura
4. tblclientes - Clientes
5. tblempleado - Empleados (con FK a tblroles)
6. tblseguridad - Usuarios/contraseñas del sistema (FK a tblempleado)
7. tblproducto - Productos (FK a tblcategoria_prod)
8. tblfactura - Facturas (FK a tblclientes, tblempleado, tblestado_factura)
9. tbldetalle_factura - Detalle de factura (FK a tblfactura, tblproducto)
10. tblinformes - Informes (tabla nueva para el módulo de informes)

## Seguridad
- RLS habilitado en todas las tablas
- Políticas CRUD para anon y authenticated (la app usa auth personalizado con tblseguridad)
- Acceso completo para anon ya que el login se maneja a nivel de aplicación con tblseguridad
*/

-- =================== TABLAS ===================

CREATE TABLE IF NOT EXISTS tblcategoria_prod (
    idcategoria         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strdescripcion      varchar(60),
    dtmfechamodifica    timestamp,
    strusuariomodifico  varchar(40)
);

CREATE TABLE IF NOT EXISTS tblroles (
    idrolempleado   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strdescripcion  varchar(50)
);

CREATE TABLE IF NOT EXISTS tblestado_factura (
    idestadofactura  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strdescripcion   varchar(30)
);

CREATE TABLE IF NOT EXISTS tblclientes (
    idcliente           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strnombre           varchar(55),
    numdocumento        bigint,
    strdireccion        varchar(70),
    strtelefono         varchar(30),
    stremail            varchar(50),
    dtmfechamodifica    timestamp,
    strusuariomodifico  varchar(40)
);

CREATE TABLE IF NOT EXISTS tblempleado (
    idempleado           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strnombre            varchar(50) NOT NULL,
    numdocumento         bigint NOT NULL,
    strdireccion         varchar(100),
    strtelefono          varchar(50),
    stremail             varchar(50),
    idrolempleado        integer REFERENCES tblroles(idrolempleado),
    dtmingreso           timestamp,
    dtmretiro            timestamp,
    strdatosadicionales  text,
    dtmfechamodifica     timestamp,
    strusuariomodifico   varchar(50)
);

CREATE TABLE IF NOT EXISTS tblseguridad (
    idseguridad          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempleado           integer NOT NULL REFERENCES tblempleado(idempleado),
    strusuario           varchar(50),
    strclave             varchar(50),
    dtmfechamodifica     timestamp,
    strusuariomodifico   varchar(50)
);

CREATE TABLE IF NOT EXISTS tblproducto (
    idproducto           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strnombre            varchar(70) NOT NULL,
    strcodigo            varchar(30) NOT NULL,
    numpreciocompra      double precision NOT NULL,
    numprecioventa       double precision NOT NULL,
    idcategoria          integer NOT NULL REFERENCES tblcategoria_prod(idcategoria),
    strdetalle           varchar(50),
    strfoto              varchar(50),
    numstock             integer,
    dtmfechamodifica     timestamp NOT NULL,
    strusuariomodifico   varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS tblfactura (
    idfactura            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dtmfecha             timestamp,
    idcliente            integer NOT NULL REFERENCES tblclientes(idcliente),
    idempleado           integer NOT NULL REFERENCES tblempleado(idempleado),
    numdescuento         double precision,
    numimpuesto          double precision,
    numvalortotal        double precision,
    idestado             integer REFERENCES tblestado_factura(idestadofactura),
    dtmfechamodifica     timestamp,
    strusuariomodifico   varchar(40)
);

CREATE TABLE IF NOT EXISTS tbldetalle_factura (
    iddetalle    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idfactura    integer NOT NULL REFERENCES tblfactura(idfactura),
    numcantidad  integer CHECK (numcantidad > 0),
    idproducto   integer NOT NULL REFERENCES tblproducto(idproducto),
    numprecio    double precision CHECK (numprecio > 0.0)
);

CREATE TABLE IF NOT EXISTS tblinformes (
    idinforme     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strtitulo     varchar(100) NOT NULL,
    strtipo       varchar(50) NOT NULL,
    strdescripcion text,
    dtmfechainicio date,
    dtmfechafin    date,
    dtmfechacreacion timestamp DEFAULT now()
);

-- =================== DATOS INICIALES ===================

INSERT INTO tblcategoria_prod (idcategoria, strdescripcion, dtmfechamodifica, strusuariomodifico) VALUES
(1, 'Tecnología', '2021-03-13 00:00:00', 'Javier'),
(2, 'Alimentos',  '2021-03-13 00:00:00', 'Javier'),
(3, 'Carnes',     '2021-03-13 00:00:00', 'Javier')
ON CONFLICT (idcategoria) DO NOTHING;

INSERT INTO tblroles (idrolempleado, strdescripcion) VALUES
(1, 'Gerente'),
(2, 'Secretaria'),
(3, 'Operario'),
(4, 'Administrativo')
ON CONFLICT (idrolempleado) DO NOTHING;

INSERT INTO tblestado_factura (idestadofactura, strdescripcion) VALUES
(1, 'Pendiente Pago'),
(2, 'Pagada'),
(3, 'Anulada'),
(4, 'Vencida')
ON CONFLICT (idestadofactura) DO NOTHING;

INSERT INTO tblclientes (idcliente, strnombre, numdocumento, strdireccion, strtelefono, stremail, dtmfechamodifica, strusuariomodifico) VALUES
(1,    'javier Alberto saldarriaga canito saludos', 71684754, 'calle la misma zzzzzz', '435346436', 'javier@gmail.com', '2021-03-12 00:00:00', 'Javier'),
(2,    'Rosmira Giraldo perez ', 71677854, 'calle 65 nto 22 33', '2345566', 'pruebarosmi@gmail.com', '2020-09-02 00:00:00', 'Javier'),
(5,    'Claudio del socorro', 456789, 'lolita avenida carlos', '33333', '3333@eee.com', '2021-03-15 00:00:00', 'Javier'),
(1012, 'davicito saldarriaguito', 2222222, 'calle la misma', '23454', 'javiy2k@gmail.com', '2019-05-07 10:27:54.253', 'javier'),
(1022, 'pedro paramo', 7777777, 'calle', '12345', 'javi@javi.com', '2020-09-02 00:00:00', 'Javier'),
(1028, 'pepe grillo en casa', 2342343, 'calle la misma', '2342353', 'asdas@sad.com', '2020-11-07 19:14:28.200', 'javier'),
(1029, '333pepe grillo en casa', 2342343, 'calle 65 c nro 91-130 interior 208', '3117185300', 'javier.saldarriaga@pascualbravo.edu.co', '2020-11-07 19:17:53.990', 'javier')
ON CONFLICT (idcliente) DO NOTHING;

INSERT INTO tblempleado (idempleado, strnombre, numdocumento, strdireccion, strtelefono, stremail, idrolempleado, dtmingreso, dtmretiro, strdatosadicionales, dtmfechamodifica, strusuariomodifico) VALUES
(1,    'Julian Alberto tabares Cano ', 71688655, 'calle 67 c nro 9092 ffff', '2345566', 'javiy2k@gmail.com', 1, '2019-01-17 00:00:00', '1900-01-01 00:00:00', 'Buen trabajador, dedicado y cumplido', '2021-03-15 00:00:00', 'Javier'),
(2,    'Rosmira Giraldo naranjo perez ', 78655543, 'Calle 8 nro 99- 34 rr', '345678', 'rosmi2809@gmail.com', 1, '2018-01-01 00:00:00', '1900-01-01 00:00:00', 'Exelente', '2020-09-11 00:00:00', 'Javier'),
(3,    'David Saldarriaga Canosito', 345678, 'calle la misma de siempre', '345678', 'david@22222.com', 3, '2019-02-06 00:00:00', '1900-01-01 00:00:00', 'es el mejor sssssss', '2021-03-12 00:00:00', 'Javier'),
(1011, 'javier saldarriaga Cano13333333333333', 71688655, 'calle 67 c nro 9092 ffff', '2345566', 'javiy2k@gmail.com', 1, '2019-01-17 00:00:00', '1900-01-01 00:00:00', 'Buen trabajador, dedicado y cumplido', '2020-03-05 00:00:00', 'Javier'),
(1016, 'javier saldarriaga Cano111', 71688655, 'calle 67 c nro 9092', '2345566', 'javiy2k@gmail.com', 1, '2019-01-01 00:00:00', '1900-01-01 00:00:00', 'Buen trabajador, dedicado y cumplido', '2020-09-02 00:00:00', 'Javier')
ON CONFLICT (idempleado) DO NOTHING;

INSERT INTO tblproducto (idproducto, strnombre, strcodigo, numpreciocompra, numprecioventa, idcategoria, strdetalle, strfoto, numstock, dtmfechamodifica, strusuariomodifico) VALUES
(1, 'tablet marca lenovo ',        '0023400',  1235600, 210000000, 1, 'nuevo de fabrica',        'ninguna', 4,  '2021-03-12 00:00:00', 'Javier'),
(2, 'TECLADOS BLUETOOTH STANDAR ', '0065400',  35600,   210000,    2, 'nuevo de fabrica2',       'ninguna', 4,  '2021-03-12 00:00:00', 'Javier'),
(4, 'pantallas ',                  '34343534', 32435,   345345,    2, 'ddddd',                   'ddddd',   23, '2020-09-02 00:00:00', 'Javier'),
(5, 'televisor led 54 pulgadas ',  '234444',   2000000, 3000000,   1, 'es un excelente producto','c:',      5,  '2021-03-15 00:00:00', 'Javier')
ON CONFLICT (idproducto) DO NOTHING;

INSERT INTO tblfactura (idfactura, dtmfecha, idcliente, idempleado, numdescuento, numimpuesto, numvalortotal, idestado, dtmfechamodifica, strusuariomodifico) VALUES
(2,  '2021-01-01 00:00:00', 1,    2, 66, 23, 123456,  1, '2021-01-01 00:00:00', 'pepe'),
(3,  '2021-01-01 00:00:00', 2,    3, 0,  0,  400000,  2, '2021-01-01 00:00:00', 'Javier'),
(6,  '2021-03-01 00:00:00', 2,    1, 5,  19, 500000,  2, '2021-03-01 00:00:00', 'julio'),
(7,  '2021-03-09 00:00:00', 5,    2, 6,  7,  5555555, 3, '2021-03-14 00:00:00', 'Javier'),
(8,  '2021-03-01 00:00:00', 1022, 2, 0,  19, 475900,  1, '2021-03-14 00:00:00', 'Javier'),
(9,  '2021-03-23 00:00:00', 1029, 2, 1,  1,  1,       2, '2021-03-14 00:00:00', 'Javier'),
(10, '2021-03-01 00:00:00', 5,    3, 5,  19, 450000,  1, '2021-03-14 00:00:00', 'Javier')
ON CONFLICT (idfactura) DO NOTHING;

INSERT INTO tblseguridad (idseguridad, idempleado, strusuario, strclave, dtmfechamodifica, strusuariomodifico) VALUES
(1002, 1,    'admin', '1234', '2021-03-12 00:00:00', 'Javier'),
(1003, 2,    'rosmi', 'asdf', '2019-08-23 14:56:31',  'Javier'),
(1005, 3,    'pepe',  '123',  '2019-09-23 15:38:31.380', 'javier'),
(2008, 1016, 'sapo',  'logo', '2020-09-02 09:46:13',  'Javier')
ON CONFLICT (idseguridad) DO NOTHING;

-- Sincronizar secuencias
SELECT setval(pg_get_serial_sequence('tblcategoria_prod', 'idcategoria'), (SELECT MAX(idcategoria) FROM tblcategoria_prod));
SELECT setval(pg_get_serial_sequence('tblclientes', 'idcliente'), (SELECT MAX(idcliente) FROM tblclientes));
SELECT setval(pg_get_serial_sequence('tblempleado', 'idempleado'), (SELECT MAX(idempleado) FROM tblempleado));
SELECT setval(pg_get_serial_sequence('tblestado_factura', 'idestadofactura'), (SELECT MAX(idestadofactura) FROM tblestado_factura));
SELECT setval(pg_get_serial_sequence('tblfactura', 'idfactura'), (SELECT MAX(idfactura) FROM tblfactura));
SELECT setval(pg_get_serial_sequence('tblproducto', 'idproducto'), (SELECT MAX(idproducto) FROM tblproducto));
SELECT setval(pg_get_serial_sequence('tblroles', 'idrolempleado'), (SELECT MAX(idrolempleado) FROM tblroles));
SELECT setval(pg_get_serial_sequence('tblseguridad', 'idseguridad'), (SELECT MAX(idseguridad) FROM tblseguridad));

-- =================== PROCEDIMIENTOS ALMACENADOS ===================

CREATE OR REPLACE PROCEDURE actualizar_categoriaprod(
    p_idcategoria integer,
    p_strdescripcion varchar(60),
    p_dtmfechamodifica timestamp,
    p_strusuariomodifico varchar(20)
)
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM tblcategoria_prod WHERE idcategoria = p_idcategoria) THEN
        INSERT INTO tblcategoria_prod (strdescripcion, dtmfechamodifica, strusuariomodifico)
        VALUES (p_strdescripcion, p_dtmfechamodifica, p_strusuariomodifico);
    ELSE
        UPDATE tblcategoria_prod
           SET strdescripcion = p_strdescripcion,
               dtmfechamodifica = p_dtmfechamodifica,
               strusuariomodifico = p_strusuariomodifico
         WHERE idcategoria = p_idcategoria;
    END IF;
END;
$$;

CREATE OR REPLACE PROCEDURE actualizar_cliente(
    p_idcliente integer,
    p_strnombre varchar(55),
    p_numdocumento bigint,
    p_strdireccion varchar(70),
    p_strtelefono varchar(30),
    p_stremail varchar(50),
    p_strusuariomodifica varchar(10),
    p_dtmfechamodifica timestamp
)
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM tblclientes WHERE idcliente = p_idcliente) THEN
        INSERT INTO tblclientes (strnombre, numdocumento, strdireccion, strtelefono, stremail, dtmfechamodifica, strusuariomodifico)
        VALUES (p_strnombre, p_numdocumento, p_strdireccion, p_strtelefono, p_stremail, p_dtmfechamodifica, p_strusuariomodifico);
    ELSE
        UPDATE tblclientes
           SET strnombre = p_strnombre,
               numdocumento = p_numdocumento,
               strdireccion = p_strdireccion,
               strtelefono = p_strtelefono,
               stremail = p_stremail,
               dtmfechamodifica = p_dtmfechamodifica,
               strusuariomodifico = p_strusuariomodifico
         WHERE idcliente = p_idcliente;
    END IF;
END;
$$;

CREATE OR REPLACE PROCEDURE actualizar_empleado(
    p_idempleado integer,
    p_strnombre varchar(50),
    p_numdocumento bigint,
    p_strdireccion varchar(50),
    p_strtelefono varchar(20),
    p_stremail varchar(50),
    p_idrolempleado integer,
    p_dtmingreso timestamp,
    p_dtmretiro timestamp,
    p_strdatosadicionales text,
    p_dtmfechamodifica timestamp,
    p_strusuariomodifico varchar(20)
)
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM tblempleado WHERE idempleado = p_idempleado) THEN
        INSERT INTO tblempleado (strnombre, numdocumento, strdireccion, strtelefono, stremail, idrolempleado, dtmingreso, dtmretiro, strdatosadicionales, dtmfechamodifica, strusuariomodifico)
        VALUES (p_strnombre, p_numdocumento, p_strdireccion, p_strtelefono, p_stremail, p_idrolempleado, p_dtmingreso, p_dtmretiro, p_strdatosadicionales, p_dtmfechamodifica, p_strusuariomodifico);
    ELSE
        UPDATE tblempleado
           SET strnombre = p_strnombre,
               numdocumento = p_numdocumento,
               strdireccion = p_strdireccion,
               strtelefono = p_strtelefono,
               stremail = p_stremail,
               idrolempleado = p_idrolempleado,
               dtmingreso = p_dtmingreso,
               dtmretiro = p_dtmretiro,
               strdatosadicionales = p_strdatosadicionales,
               dtmfechamodifica = p_dtmfechamodifica,
               strusuariomodifico = p_strusuariomodifico
         WHERE idempleado = p_idempleado;
    END IF;
END;
$$;

CREATE OR REPLACE PROCEDURE actualizar_factura(
    p_idfactura integer,
    p_dtmfecha timestamp,
    p_idcliente integer,
    p_idempleado integer,
    p_numdescuento double precision,
    p_numimpuesto double precision,
    p_numvalortotal double precision,
    p_idestado integer,
    p_dtmfechamodifica timestamp,
    p_strusuariomodifico varchar(10)
)
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM tblfactura WHERE idfactura = p_idfactura) THEN
        INSERT INTO tblfactura (dtmfecha, idcliente, idempleado, numdescuento, numimpuesto, numvalortotal, idestado, dtmfechamodifica, strusuariomodifico)
        VALUES (p_dtmfecha, p_idcliente, p_idempleado, p_numdescuento, p_numimpuesto, p_numvalortotal, p_idestado, p_dtmfechamodifica, p_strusuariomodifico);
    ELSE
        UPDATE tblfactura
           SET dtmfecha = p_dtmfecha,
               idcliente = p_idcliente,
               idempleado = p_idempleado,
               numdescuento = p_numdescuento,
               numimpuesto = p_numimpuesto,
               numvalortotal = p_numvalortotal,
               idestado = p_idestado,
               dtmfechamodifica = p_dtmfechamodifica,
               strusuariomodifico = p_strusuariomodifico
         WHERE idfactura = p_idfactura;
    END IF;
END;
$$;

CREATE OR REPLACE PROCEDURE actualizar_producto(
    p_idproducto integer,
    p_strnombre varchar(70),
    p_strcodigo varchar(30),
    p_numpreciocompra double precision,
    p_numprecioventa double precision,
    p_idcategoria integer,
    p_strdetalle varchar(50),
    p_strfoto varchar(50),
    p_numstock integer,
    p_dtmfechamodifica timestamp,
    p_strusuariomodifico varchar(40)
)
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM tblproducto WHERE idproducto = p_idproducto) THEN
        INSERT INTO tblproducto (strnombre, strcodigo, numpreciocompra, numprecioventa, idcategoria, strdetalle, strfoto, numstock, dtmfechamodifica, strusuariomodifico)
        VALUES (p_strnombre, p_strcodigo, p_numpreciocompra, p_numprecioventa, p_idcategoria, p_strdetalle, p_strfoto, p_numstock, p_dtmfechamodifica, p_strusuariomodifico);
    ELSE
        UPDATE tblproducto
           SET strnombre = p_strnombre,
               strcodigo = p_strcodigo,
               numpreciocompra = p_numpreciocompra,
               numprecioventa = p_numprecioventa,
               idcategoria = p_idcategoria,
               strdetalle = p_strdetalle,
               strfoto = p_strfoto,
               numstock = p_numstock,
               dtmfechamodifica = p_dtmfechamodifica,
               strusuariomodifico = p_strusuariomodifico
         WHERE idproducto = p_idproducto;
    END IF;
END;
$$;

CREATE OR REPLACE PROCEDURE actualizar_seguridad(
    p_idempleado integer,
    p_strusuario varchar(50),
    p_strclave varchar(50),
    p_dtmfechamodifica timestamp,
    p_strusuariomodifico varchar(10)
)
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM tblseguridad WHERE idempleado = p_idempleado) THEN
        INSERT INTO tblseguridad (idempleado, strusuario, strclave, dtmfechamodifica, strusuariomodifico)
        VALUES (p_idempleado, p_strusuario, p_strclave, p_dtmfechamodifica, p_strusuariomodifico);
    ELSE
        UPDATE tblseguridad
           SET idempleado = p_idempleado,
               strusuario = p_strusuario,
               strclave = p_strclave,
               dtmfechamodifica = p_dtmfechamodifica,
               strusuariomodifico = p_strusuariomodifico
         WHERE idempleado = p_idempleado;
    END IF;
END;
$$;

CREATE OR REPLACE PROCEDURE eliminar_categoriaproducto(p_idcategoria integer)
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM tblcategoria_prod WHERE idcategoria = p_idcategoria;
END;
$$;

CREATE OR REPLACE PROCEDURE eliminar_cliente(p_idcliente integer)
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM tblclientes WHERE idcliente = p_idcliente;
END;
$$;

CREATE OR REPLACE PROCEDURE eliminar_empleado(p_idempleado integer)
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM tblempleado WHERE idempleado = p_idempleado;
END;
$$;

CREATE OR REPLACE PROCEDURE eliminar_producto(p_idproducto integer)
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM tblproducto WHERE idproducto = p_idproducto;
END;
$$;

CREATE OR REPLACE PROCEDURE eliminar_seguridad(p_idempleado integer)
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM tblseguridad WHERE idempleado = p_idempleado;
END;
$$;

CREATE OR REPLACE FUNCTION spconsultafactura()
RETURNS TABLE (
    nro_factura integer,
    fecha       text,
    cliente     varchar(55),
    empleado    varchar(50),
    estado      varchar(30)
)
LANGUAGE sql AS $$
    SELECT f.idfactura,
           to_char(f.dtmfecha, 'DD/MM/YYYY'),
           c.strnombre,
           e.strnombre,
           ef.strdescripcion
      FROM tblfactura f
      JOIN tblestado_factura ef ON f.idestado = ef.idestadofactura
      JOIN tblclientes c ON f.idcliente = c.idcliente
      JOIN tblempleado e ON f.idempleado = e.idempleado;
$$;

-- =================== RLS ===================
-- La app usa autenticación personalizada con tblseguridad, no Supabase Auth.
-- Por eso se permite acceso anon + authenticated en todas las tablas.

ALTER TABLE tblcategoria_prod ENABLE ROW LEVEL SECURITY;
ALTER TABLE tblroles ENABLE ROW LEVEL SECURITY;
ALTER TABLE tblestado_factura ENABLE ROW LEVEL SECURITY;
ALTER TABLE tblclientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE tblempleado ENABLE ROW LEVEL SECURITY;
ALTER TABLE tblseguridad ENABLE ROW LEVEL SECURITY;
ALTER TABLE tblproducto ENABLE ROW LEVEL SECURITY;
ALTER TABLE tblfactura ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbldetalle_factura ENABLE ROW LEVEL SECURITY;
ALTER TABLE tblinformes ENABLE ROW LEVEL SECURITY;

-- Políticas para todas las tablas (anon + authenticated)
-- tblcategoria_prod
DROP POLICY IF EXISTS "anon_crud_tblcategoria_prod_select" ON tblcategoria_prod;
CREATE POLICY "anon_crud_tblcategoria_prod_select" ON tblcategoria_prod FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_crud_tblcategoria_prod_insert" ON tblcategoria_prod;
CREATE POLICY "anon_crud_tblcategoria_prod_insert" ON tblcategoria_prod FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblcategoria_prod_update" ON tblcategoria_prod;
CREATE POLICY "anon_crud_tblcategoria_prod_update" ON tblcategoria_prod FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblcategoria_prod_delete" ON tblcategoria_prod;
CREATE POLICY "anon_crud_tblcategoria_prod_delete" ON tblcategoria_prod FOR DELETE TO anon, authenticated USING (true);

-- tblroles
DROP POLICY IF EXISTS "anon_crud_tblroles_select" ON tblroles;
CREATE POLICY "anon_crud_tblroles_select" ON tblroles FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_crud_tblroles_insert" ON tblroles;
CREATE POLICY "anon_crud_tblroles_insert" ON tblroles FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblroles_update" ON tblroles;
CREATE POLICY "anon_crud_tblroles_update" ON tblroles FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblroles_delete" ON tblroles;
CREATE POLICY "anon_crud_tblroles_delete" ON tblroles FOR DELETE TO anon, authenticated USING (true);

-- tblestado_factura
DROP POLICY IF EXISTS "anon_crud_tblestado_factura_select" ON tblestado_factura;
CREATE POLICY "anon_crud_tblestado_factura_select" ON tblestado_factura FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_crud_tblestado_factura_insert" ON tblestado_factura;
CREATE POLICY "anon_crud_tblestado_factura_insert" ON tblestado_factura FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblestado_factura_update" ON tblestado_factura;
CREATE POLICY "anon_crud_tblestado_factura_update" ON tblestado_factura FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblestado_factura_delete" ON tblestado_factura;
CREATE POLICY "anon_crud_tblestado_factura_delete" ON tblestado_factura FOR DELETE TO anon, authenticated USING (true);

-- tblclientes
DROP POLICY IF EXISTS "anon_crud_tblclientes_select" ON tblclientes;
CREATE POLICY "anon_crud_tblclientes_select" ON tblclientes FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_crud_tblclientes_insert" ON tblclientes;
CREATE POLICY "anon_crud_tblclientes_insert" ON tblclientes FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblclientes_update" ON tblclientes;
CREATE POLICY "anon_crud_tblclientes_update" ON tblclientes FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblclientes_delete" ON tblclientes;
CREATE POLICY "anon_crud_tblclientes_delete" ON tblclientes FOR DELETE TO anon, authenticated USING (true);

-- tblempleado
DROP POLICY IF EXISTS "anon_crud_tblempleado_select" ON tblempleado;
CREATE POLICY "anon_crud_tblempleado_select" ON tblempleado FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_crud_tblempleado_insert" ON tblempleado;
CREATE POLICY "anon_crud_tblempleado_insert" ON tblempleado FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblempleado_update" ON tblempleado;
CREATE POLICY "anon_crud_tblempleado_update" ON tblempleado FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblempleado_delete" ON tblempleado;
CREATE POLICY "anon_crud_tblempleado_delete" ON tblempleado FOR DELETE TO anon, authenticated USING (true);

-- tblseguridad
DROP POLICY IF EXISTS "anon_crud_tblseguridad_select" ON tblseguridad;
CREATE POLICY "anon_crud_tblseguridad_select" ON tblseguridad FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_crud_tblseguridad_insert" ON tblseguridad;
CREATE POLICY "anon_crud_tblseguridad_insert" ON tblseguridad FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblseguridad_update" ON tblseguridad;
CREATE POLICY "anon_crud_tblseguridad_update" ON tblseguridad FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblseguridad_delete" ON tblseguridad;
CREATE POLICY "anon_crud_tblseguridad_delete" ON tblseguridad FOR DELETE TO anon, authenticated USING (true);

-- tblproducto
DROP POLICY IF EXISTS "anon_crud_tblproducto_select" ON tblproducto;
CREATE POLICY "anon_crud_tblproducto_select" ON tblproducto FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_crud_tblproducto_insert" ON tblproducto;
CREATE POLICY "anon_crud_tblproducto_insert" ON tblproducto FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblproducto_update" ON tblproducto;
CREATE POLICY "anon_crud_tblproducto_update" ON tblproducto FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblproducto_delete" ON tblproducto;
CREATE POLICY "anon_crud_tblproducto_delete" ON tblproducto FOR DELETE TO anon, authenticated USING (true);

-- tblfactura
DROP POLICY IF EXISTS "anon_crud_tblfactura_select" ON tblfactura;
CREATE POLICY "anon_crud_tblfactura_select" ON tblfactura FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_crud_tblfactura_insert" ON tblfactura;
CREATE POLICY "anon_crud_tblfactura_insert" ON tblfactura FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblfactura_update" ON tblfactura;
CREATE POLICY "anon_crud_tblfactura_update" ON tblfactura FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblfactura_delete" ON tblfactura;
CREATE POLICY "anon_crud_tblfactura_delete" ON tblfactura FOR DELETE TO anon, authenticated USING (true);

-- tbldetalle_factura
DROP POLICY IF EXISTS "anon_crud_tbldetalle_factura_select" ON tbldetalle_factura;
CREATE POLICY "anon_crud_tbldetalle_factura_select" ON tbldetalle_factura FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_crud_tbldetalle_factura_insert" ON tbldetalle_factura;
CREATE POLICY "anon_crud_tbldetalle_factura_insert" ON tbldetalle_factura FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tbldetalle_factura_update" ON tbldetalle_factura;
CREATE POLICY "anon_crud_tbldetalle_factura_update" ON tbldetalle_factura FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tbldetalle_factura_delete" ON tbldetalle_factura;
CREATE POLICY "anon_crud_tbldetalle_factura_delete" ON tbldetalle_factura FOR DELETE TO anon, authenticated USING (true);

-- tblinformes
DROP POLICY IF EXISTS "anon_crud_tblinformes_select" ON tblinformes;
CREATE POLICY "anon_crud_tblinformes_select" ON tblinformes FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_crud_tblinformes_insert" ON tblinformes;
CREATE POLICY "anon_crud_tblinformes_insert" ON tblinformes FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblinformes_update" ON tblinformes;
CREATE POLICY "anon_crud_tblinformes_update" ON tblinformes FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_crud_tblinformes_delete" ON tblinformes;
CREATE POLICY "anon_crud_tblinformes_delete" ON tblinformes FOR DELETE TO anon, authenticated USING (true);

-- =================== ÍNDICES ===================
CREATE INDEX IF NOT EXISTS idx_tblproducto_categoria ON tblproducto(idcategoria);
CREATE INDEX IF NOT EXISTS idx_tblfactura_cliente ON tblfactura(idcliente);
CREATE INDEX IF NOT EXISTS idx_tblfactura_empleado ON tblfactura(idempleado);
CREATE INDEX IF NOT EXISTS idx_tblfactura_estado ON tblfactura(idestado);
CREATE INDEX IF NOT EXISTS idx_tbldetalle_factura_factura ON tbldetalle_factura(idfactura);
CREATE INDEX IF NOT EXISTS idx_tbldetalle_factura_producto ON tbldetalle_factura(idproducto);
CREATE INDEX IF NOT EXISTS idx_tblempleado_rol ON tblempleado(idrolempleado);
